### ISSUE TITLE
Adding tool version number to the validator report

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/vcf-validator#134]
Currently there is no way to to ensure compatibility between the report generated by the validator and that consumed by the debugulator. Adding the tool version number to the validator report would allow the debugulator to check that it is compatible.

**Comment by jmmut** [comment]
@srbcheema1, you are more familiar with the validator than other students, so it would be better if @ManeshNarayan finished this PR, also because his proposal is about performance benchmarking and it will be helpful learning about how we use ODB (writing to a DB is potentially a bottleneck).

The PR is not complete, because if the debugulator is going to perform a compatibility check, the version information needs to be present in the DB report.

To add information to the DB report we need to create a small struct in inc/vcf/error.hpp, as ODB is an object-to-DB mapping library. I guess something as simple as 

```
#pragma db object
struct ReportVersion
{
    std::string version;
};
```
 can do the job. Look at src/vcf/odb-report.cpp to understand how an object in memory is written to the DB file (we are using sqlite, which is a DB that is backed by a local file).

**Comment by tcezard** [comment]
This will be tracked in EVA-2048: closing
