### ISSUE TITLE
Pipe output to custom file ?

### ISSUE THREAD

**Issue by sigven** [EBIvariation/vcf-validator#145]
Hi,

Thanks for a great tool! I just tried out the latest release (0.8). I cannot seem to find a way to forward the output to a designated file, i.e.

`vcf_validator -i example.vcf.gz --level error > vcf_validation.txt 2>/dev/null`

The vcf_validation.txt file is empty. I am only seeing an output file with the input filename as the prefix in addition to a random number. 

regards,
Sigve

**Comment by srbcheema1** [comment]
There is some confusion in the term `output` in the line `forward the output to a designated file`.

Term `output` is ambiguous having two meanings here. just tell which one would you like to redirect to a file.

Output 1
```
$ vcf_validdator -i passed1.vcf 
[info] Reading from input file...
[info] Summary report written to : passed1.vcf.errors_summary.1530777921807.txt
[info] According to the VCF specification, the input file is not valid
```

Output 2
```
$ cat passed1.vcf.errors_summary.1530777921807.txt 
According to the VCF specification, the input file is not valid
Error: The fileformat declaration is not valid (the line must start with ##fileformat= and the value must be one of 'VCFv4.1', 'VCFv4.2' or 'VCFv4.3'). This occurs 1 time(s), first time in line 1.
```

**Comment by sigven** [comment]
Apologees, my bad. I would ideally like to know how vcf_validator should be called in order to forward *Output 1* to a designated file.

regards,
Sigve

**Comment by srbcheema1** [comment]
```
$ vcf_validator -i passed1.vcf > vcf_validation.txt 2>&1
$ cat vcf_validation.txt
[info] Reading from input file...
[info] Summary report written to : passed1.vcf.errors_summary.1530778642693.txt
[info] According to the VCF specification, the input file is valid

```

**Comment by jmmut** [comment]
Currently you can change the ouput directory for the reports (output 2), but you will have to rename the file afterwards if you don't like the name passed1.vcf.errors_summary.1530777921807.txt

**Comment by srbcheema1** [comment]
Actually till now the vcf-validator has no support to specify the output file for `Output 2`.

**Comment by sigven** [comment]
Ok, got it. I believe have utilized the full `Output 2` in previous versions to tell users what is wrong with their VCF files, but I maybe wrong here.

**Comment by jmmut** [comment]
Yes, we've been struggling making the interface clear. In older versions the report (output 2) could be written to a file or to standard output (and redirect with `>`) but we found it was not very clean and a bit confusing to interleave logging messages (output 1) and the report, unless you redirected each one to a different place (using both `>` and `2>`). 

This got worse when we added more types of reports (parameter `-r`). That's why we opted to always write each report in its own file. Right now there's the `summary` (default) which groups errors of the same type, the `text` with a line for each occurrence of an error, and the `database` to be used with the debugulator.

We are also thinking about writing every message to standard output, and not using standard error at all, so that the messages can be handled with only `>` .

Thanks for the feedback!
