### ISSUE TITLE
Latest release is experimental?

### ISSUE THREAD

**Issue by CholoTook** [EBIvariation/vcf-validator#194]
Hi, which release should I use? The latest release seems to be experimental, which I don't want. thx.

**Comment by jmmut** [comment]
Hi, I recommend using v0.9.2 anyway.

v0.9.2 is experimental but only for some new features of the assembly checker. They are explained  in https://github.com/EBIvariation/vcf-validator/releases. The validator the same, or slightly more updated compared to v0.9.1.

If you **plan to use those features**, the behaviour of them might change (improve) in the future. v0.9.1 doesn't have those features at all, so if you want to use them now, v0.9.2 is your only option.

If you **don't plan to use those features** then v0.9.2 is as stable as v0.9.1, or even more stable because v0.9.2 has some small improvements over v0.9.1.

Let me know if this is clear and I'll close the issue.

**Comment by CholoTook** [comment]
Thanks, that's clear, but the title isn't. Not sure if you could word it better. e.g. 

Release v0.9.2, 16 August 2019

This release has some small improvements over v0.9.1.

It also includes some experimental features of the assembly checker, described below. Please note that these experimental features may change.


I know this seems trivial, but it does confuse people.

**Comment by jmmut** [comment]
Thanks for the feedback. It's hard to convey all the meaning and still be concise. I edited the release notes mentioning your concerns.

**Comment by CholoTook** [comment]
Thanks so much JM!

All the best,
