### ISSUE TITLE
MacOS validator not running on Intel Monterey

### ISSUE THREAD

**Issue by maxglycine** [EBIvariation/vcf-validator#226]
I am getting zsh: exec format error: ./vcf_validator_linux when running MacOS Monterey on Intel architecture. Are my only options to run this on a linux distro (Ubuntu) or compile it on my machine?

**Comment by tcezard** [comment]
We've [struggled](https://github.com/EBIvariation/vcf-validator/pull/224/commits/72f786cf766984020125a8ff22e71bf1f3e0e122) to compile some of the dependencies on mac for the latest release which is why it's missing at the moment. This is due to some of the recent architecture changes in Mac OSX.
You can use the [previous release](https://github.com/EBIvariation/vcf-validator/releases/tag/v0.9.4) which should still work.
If you want to try compiling the code the build recipes are in the [github workflow](https://github.com/EBIvariation/vcf-validator/blob/master/.github/workflows/build.yml)  but my guess is you'll hit the same issues we had.
We have an internal ticket to get it working on MAC OSX at a later date.
