### ISSUE TITLE
Error: AD field expects 3, found 2

### ISSUE THREAD

**Issue by thomasyu888** [EBIvariation/vcf-validator#75]
In the 4.2 spec it says:

```We have the AD field, which is a vector of 2 values per sample. ```

Does the spec need to be changed or does the tool need to be changed.

Example row:
```
2	217498305	.	T	TGCTGCC	1.3	.	.	GT:AD:DP	0/1:10,10,1:20	0/0:30,5:35
```

**Comment by Anishka0107** [comment]
Could you please provide the complete meta header definition of the VCF file?
What version of the validator are you using?
The first sample `0/1:10,10,1:20` contains 3 values (10,10,1) for AD and the second one `0/0:30,5:35` contains 2 values (30,5). Is that intended?
The error you are getting is possibly because of a meta header definition provided in the vcf file for tag AD.
Also, the definition provided actually applies to BCF.

**Comment by thomasyu888** [comment]
Sorry I opened up an issue here: https://github.com/vcftools/vcftools/issues/82#issuecomment-311564778 and they explained it for me.  This isn't an error on your part.  Thanks!
