### ISSUE TITLE
SAMPLE metadata wrongly formatted?

### ISSUE THREAD

**Issue by sigven** [EBIvariation/vcf-validator#99]
Hi,

I have a VCF with sample information encoded as follows:

##SAMPLE=<ID=T2,Genomes=Tumor>

During vcf-validation I get an error saying:
SAMPLE metadata Genomes is not a valid string (maybe it contains quotes?)

According the the VCF spec the SAMPLE info should be specified as follows:

##SAMPLE=<ID=S_ID,Genomes=G1_ID;G2_ID; ...;GK_ID,Mixture=N1;N2; ...;NK,Description=S1;S2; ...;SK>

So from my line above, I cannot really see that this is wrongly formatted?

**Comment by jmmut** [comment]
I guess this is for version VCFv4.2? for 4.3 it doesn't give any error. Indeed, this is a bit strange, we'll look further into it.

**Comment by Anishka0107** [comment]
This error is occurring because VCF v4.2 and v4.1 require `SAMPLE` to have metadata `Mixture` and `Description` as well. 
It shouldn't occur if the line is changed to:
`##SAMPLE=<ID=T2,Genomes=Tumor,Mixture=some_mixture,Description="some_description">`
 
But the error message displayed is misleading.

**Comment by tcezard** [comment]
Tracked now in EVA-2054: closing
